/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "surface-dim": "#131313",
        "on-background": "#e2e2e2",
        "inverse-primary": "#006e2d",
        "tertiary-container": "#ff7868",
        "surface-container-low": "#1b1b1b",
        "outline-variant": "#3d4a3d",
        "surface-bright": "#393939",
        "surface-container-highest": "#353535",
        "surface-container-high": "#2a2a2a",
        "secondary-fixed-dim": "#ffb3b5",
        "on-tertiary-fixed-variant": "#930005",
        "tertiary-fixed-dim": "#ffb4aa",
        "surface-variant": "#353535",
        "on-error": "#690005",
        "surface-tint": "#53e076",
        "secondary": "#ffb3b5",
        "surface-container-lowest": "#0e0e0e",
        "tertiary": "#ffb4aa",
        "on-secondary-fixed-variant": "#920027",
        "on-primary-fixed-variant": "#005320",
        "surface": "#131313",
        "outline": "#869585",
        "on-secondary-fixed": "#40000c",
        "on-secondary-container": "#fff1f1",
        "on-primary": "#003914",
        "background": "#131313",
        "on-primary-fixed": "#002108",
        "on-tertiary-container": "#770003",
        "primary-fixed": "#72fe8f",
        "on-primary-container": "#004118",
        "inverse-on-surface": "#303030",
        "secondary-fixed": "#ffdada",
        "on-tertiary": "#690003",
        "error": "#ffb4ab",
        "on-secondary": "#680019",
        "primary": "#53e076",
        "primary-fixed-dim": "#53e076",
        "on-tertiary-fixed": "#410001",
        "inverse-surface": "#e2e2e2",
        "primary-container": "#1db954",
        "tertiary-fixed": "#ffdad5",
        "secondary-container": "#de0541",
        "on-error-container": "#ffdad6",
        "error-container": "#93000a",
        "surface-container": "#1f1f1f",
        "on-surface-variant": "#bccbb9",
        "on-surface": "#e2e2e2"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "xl": "80px",
        "base": "8px",
        "md": "24px",
        "sm": "12px",
        "gutter": "16px",
        "xs": "4px",
        "lg": "48px",
        "container-margin": "20px"
      },
      "fontFamily": {
        "label-caps": ["Plus Jakarta Sans"],
        "display-lg": ["Plus Jakarta Sans"],
        "body-lg": ["Be Vietnam Pro"],
        "headline-sm": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "body-md": ["Be Vietnam Pro"]
      },
      "fontSize": {
        "label-caps": ["12px", {"lineHeight": "1", "letterSpacing": "0.1em", "fontWeight": "600"}],
        "display-lg": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "800"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "headline-sm": ["24px", {"lineHeight": "1.3", "fontWeight": "700"}],
        "headline-md": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-md": ["16px", {"lineHeight": "1.5", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
